/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Board } from './board';


export interface Game { 
    id?: number;
    status?: Game.StatusEnum;
    turn?: Game.TurnEnum;
    winner?: Game.WinnerEnum;
    pitCount?: number;
    againstComputer?: boolean;
    creationDate?: string;
    boards?: Array<Board>;
}
export namespace Game {
    export type StatusEnum = 'INITIALIZED' | 'RUNNING' | 'OVER';
    export const StatusEnum = {
        Initialized: 'INITIALIZED' as StatusEnum,
        Running: 'RUNNING' as StatusEnum,
        Over: 'OVER' as StatusEnum
    };
    export type TurnEnum = 'A' | 'B';
    export const TurnEnum = {
        A: 'A' as TurnEnum,
        B: 'B' as TurnEnum
    };
    export type WinnerEnum = 'A' | 'B';
    export const WinnerEnum = {
        A: 'A' as WinnerEnum,
        B: 'B' as WinnerEnum
    };
}


