/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoardResponseDto } from './boardResponseDto';


export interface BoardHeaderResponseDto { 
    boardResponseDtos?: Array<BoardResponseDto>;
    turn?: BoardHeaderResponseDto.TurnEnum;
}
export namespace BoardHeaderResponseDto {
    export type TurnEnum = 'BLUE' | 'RED';
    export const TurnEnum = {
        Blue: 'BLUE' as TurnEnum,
        Red: 'RED' as TurnEnum
    };
}


