/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Game } from './game';


export interface Board { 
    id?: number;
    game?: Game;
    pit?: number;
    playerSide?: Board.PlayerSideEnum;
    tokenCount?: number;
    kalah?: boolean;
    creationDate?: string;
    updateDate?: string;
}
export namespace Board {
    export type PlayerSideEnum = 'A' | 'B';
    export const PlayerSideEnum = {
        A: 'A' as PlayerSideEnum,
        B: 'B' as PlayerSideEnum
    };
}


