/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoardResponseDto } from './boardResponseDto';


export interface GameResponseDto { 
    pitCount?: number;
    id?: number;
    playerRedName?: string;
    playerBlueName?: string;
    turn?: GameResponseDto.TurnEnum;
    status?: GameResponseDto.StatusEnum;
    winner?: GameResponseDto.TurnEnum;
    boardResponseDtos?: Array<BoardResponseDto>;
}
export namespace GameResponseDto {
    export type TurnEnum = 'BLUE' | 'RED';
    export const TurnEnum = {
        Blue: 'BLUE' as TurnEnum,
        Red: 'RED' as TurnEnum
    };
    export type StatusEnum = 'ACTIVE' | 'GAME_OVER_DRAW' | 'GAME_OVER';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        GameOverDraw: 'GAME_OVER_DRAW' as StatusEnum,
        GameOver: 'GAME_OVER' as StatusEnum
    };
}


